package com.freelancer.utils;

public enum TypeWS {
    NOTIFICATIONS, ADD_NOTIFICATION, REMOVE_NOTIFICATION, READ_NOTIFICATION, READ_ALL_NOTIFICATION, REMOVE_ALL_NOTIFICATION, ACTIVE_USERS, ADD_ACTIVE_USERS, REMOVE_ACTIVE_USERS, CONVERSATIONS, UPDATE_CONVERSATIONS, READ_CONVERSATION_USER_ID, UPDATE_REALTIME_CONVERSATION, UPDATE_REALTIME_CONVERSATION_RECALL, UPDATE_CONVERSATION_RECALL, UPDATE_CONVERSATION_ME
}
