const sampleData = [
  {
    key: 1,
    jobPostName: "Tuyển dụng lập trình viên Frontend React",
    author: "Nguyễn Văn An",
    reason: "Nội dung không phù hợp",
    reporter: "Trần Thị Bình",
    datePosted: "2024-01-15",
  },
  {
    key: 2,
    jobPostName: "Cần tuyển kế toán trưởng",
    author: "Lê Thị Hương",
    reason: "Thông tin lừa đảo",
    reporter: "Phạm Văn Cường",
    datePosted: "2024-01-14",
  },
  {
    key: 3,
    jobPostName: "Tuyển nhân viên kinh doanh",
    author: "Đỗ Văn Dũng",
    reason: "Spam nhiều lần",
    reporter: "Hoàng Thị Em",
    datePosted: "2024-01-13",
  },
  {
    key: 4,
    jobPostName: "Tuyển gấp nhân viên marketing",
    author: "Trần Văn Phúc",
    reason: "Thông tin sai sự thật",
    reporter: "Lê Văn Giang",
    datePosted: "2024-01-12",
  },
  {
    key: 5,
    jobPostName: "Cần tuyển thiết kế đồ họa",
    author: "Phạm Thị Hà",
    reason: "Nội dung không phù hợp",
    reporter: "Nguyễn Thị Hoa",
    datePosted: "2024-01-11",
  },
  {
    key: 6,
    jobPostName: "Tuyển nhân viên bán hàng",
    author: "Vũ Văn Hiếu",
    reason: "Lừa đảo",
    reporter: "Trần Văn Inh",
    datePosted: "2024-01-10",
  },
  {
    key: 7,
    jobPostName: "Tuyển dụng Backend Developer",
    author: "Nguyễn Thị Kiều",
    reason: "Thông tin không rõ ràng",
    reporter: "Lê Văn Linh",
    datePosted: "2024-01-09",
  },
  {
    key: 8,
    jobPostName: "Cần tuyển nhân viên IT helpdesk",
    author: "Trần Văn Minh",
    reason: "Spam",
    reporter: "Phạm Thị Ngọc",
    datePosted: "2024-01-08",
  },
  {
    key: 9,
    jobPostName: "Tuyển quản lý nhà hàng",
    author: "Lê Thị Oanh",
    reason: "Nội dung không phù hợp",
    reporter: "Hoàng Văn Phú",
    datePosted: "2024-01-07",
  },
  {
    key: 10,
    jobPostName: "Tuyển nhân viên chăm sóc khách hàng",
    author: "Phạm Văn Quang",
    reason: "Thông tin sai lệch",
    reporter: "Nguyễn Thị Rương",
    datePosted: "2024-01-06",
  },
  {
    key: 11,
    jobPostName: "Tuyển kỹ sư phần mềm",
    author: "Hoàng Văn Sơn",
    reason: "Lừa đảo",
    reporter: "Trần Thị Thảo",
    datePosted: "2024-01-05",
  },
  {
    key: 12,
    jobPostName: "Cần tuyển nhân viên tư vấn",
    author: "Nguyễn Thị Uyên",
    reason: "Spam nhiều lần",
    reporter: "Lê Văn Vũ",
    datePosted: "2024-01-04",
  },
  {
    key: 13,
    jobPostName: "Tuyển dụng UI/UX Designer",
    author: "Trần Văn Xuân",
    reason: "Nội dung không phù hợp",
    reporter: "Phạm Thị Yến",
    datePosted: "2024-01-03",
  },
  {
    key: 14,
    jobPostName: "Tuyển nhân viên kỹ thuật",
    author: "Lê Văn Anh",
    reason: "Thông tin không rõ ràng",
    reporter: "Nguyễn Văn Bách",
    datePosted: "2024-01-02",
  },
  {
    key: 15,
    jobPostName: "Cần tuyển nhân viên SEO",
    author: "Phạm Thị Cúc",
    reason: "Lừa đảo",
    reporter: "Trần Văn Dương",
    datePosted: "2024-01-01",
  },
  {
    key: 16,
    jobPostName: "Tuyển nhân viên content",
    author: "Hoàng Văn Em",
    reason: "Spam",
    reporter: "Lê Thị Phương",
    datePosted: "2023-12-31",
  },
  {
    key: 17,
    jobPostName: "Tuyển dụng PHP Developer",
    author: "Nguyễn Văn Giáp",
    reason: "Nội dung không phù hợp",
    reporter: "Trần Thị Hằng",
    datePosted: "2023-12-30",
  },
  {
    key: 18,
    jobPostName: "Cần tuyển nhân viên QA/QC",
    author: "Trần Thị Lan",
    reason: "Thông tin sai sự thật",
    reporter: "Phạm Văn Mạnh",
    datePosted: "2023-12-29",
  },
  {
    key: 19,
    jobPostName: "Tuyển nhân viên quản lý dự án",
    author: "Lê Văn Nam",
    reason: "Spam nhiều lần",
    reporter: "Nguyễn Thị Oanh",
    datePosted: "2023-12-28",
  },
  {
    key: 20,
    jobPostName: "Tuyển dụng DevOps Engineer",
    author: "Phạm Văn Phong",
    reason: "Thông tin không rõ ràng",
    reporter: "Trần Thị Quỳnh",
    datePosted: "2023-12-27",
  },
];

export default sampleData;
